routes/web.php
<?php
Route::get('/',['uses'=>'IndexController@execute','as'=>'home']);

Route::resource('article','ArticlesController',[
    'parameters'=> [
        'articles'=>'alias'
    ]
]);

    Route::group(['prefix'=>'admin','middleware'=>'auth'],function (){
        Route::get('/',['uses'=>'Admin\BookController@index']);
        Route::resource('articless','Admin\BookController');
    });


Auth::routes();

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable = ['name','email','text','created_at','updated_at'];
}

app/Firm.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Firm extends Model
{
    public function phone(){
        return $this->hasOne('App\Phone','FirmID');
    }

}

app/Phone.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Phone extends Model
{
    public function firms(){
    return $this->belongsTo('App\Firm','FirmID');
}
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Book;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $book = Book::all();    //Получаємо дані з бази даних


        return view('admin.home',array(  //Передаємо дані в Види
            'books'=>$book,
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $date = Book::find($id);




        return view('site.articles',array(  //Передаємо дані в Види
            'date'=>$date,
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $date2 = $request;

        //$pages = $test = DB::update("UPDATE `Books` SET `name` = '$date2->name', `email` = '$date2->email', `text` = '$date2->text' WHERE `Books`.`id` = $id");

        if ($pages = $test = DB::update("UPDATE `Books` SET `name` = '$date2->name', `email` = '$date2->email', `text` = '$date2->text' WHERE `Books`.`id` = $id")){
            return redirect('admin')->with('status','Материал обновлен');

        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy( $id)
    {
        $flight = Book::find($id);


        if ($flight->delete()){
            return redirect('admin/articless')->with('status','Дані удалены');
        }
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use App\Phone;
use Illuminate\Http\Request;
use DB;
use Illuminate\Support\Facades\Validator;

class ArticlesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


        $book = $test = DB::select("SELECT * FROM `Books` ORDER BY `Books`.`created_at` DESC");



        return view('site.book',array(
            'books'=>$book,
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->except('_token');


        $massages =[    //Формуємо свої ошибки повідомлень
            'required'=>'Поле :attribute обовязкове для заповнення',
            'email'=>'Поле :attribute повине бути email адресом',

        ];
        $validator = Validator::make($input,
            [
                'name'=>'required|max:255',
                'email'=>'required|email',
                'text'=>'required'
            ],$massages);

        if ($validator->fails()){

            return redirect()->route('article.index')->withErrors($validator)->withInput();
        }

        $data = $request->all();

        $books = new Book();

        $books->fill($data);
        if ($books->save()){
            return redirect('article')->with('status','Нові дані записані');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/IndexController.php
<?php

namespace App\Http\Controllers;

use App\Firm;

use Illuminate\Http\Request;



use DB;

class IndexController extends Controller
{
    //
    public function execute(Request $request){

        $pages = Firm::all();

        $inquiry = DB::select("select * from Firms where id not in (select FirmID from Phones)");
        $inquiry2 = DB::select("select * , COUNT(*) from Firms f, Phones p where f.id = p.FirmID GROUP by p.FirmID HAVING COUNT(*) >= 2");
        $inquiry3 = DB::select("select * , COUNT(*) from Firms f, Phones p where f.id = p.FirmID GROUP by p.FirmID HAVING COUNT(*) < 2");
        $inquiry4 = DB::select("select * , COUNT(*) from Firms f, Phones p where f.id = p.FirmID GROUP by p.FirmID ORDER by COUNT(*) DESC LIMIT 1");


        return view('site.index',array(
            'pages'=>$pages,
            'inquiry'=>$inquiry,
            'inquiry2'=>$inquiry2,
            'inquiry3'=>$inquiry3,
            'inquiry4'=>$inquiry4
        ));
    }

}

resources/views/admin/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">



                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif


                        @if(isset($books))
                            <div id="content-page" class="content group">
                                <div class="hentry group">
                                    <div class="short-table white">
                                        <table style="width: 100%" cellspacing="0" cellpadding="0">
                                            <thead>
                                            <tr>
                                                <th class="align-left">ID</th>
                                                <th>name</th>
                                                <th>email</th>
                                                <th>text</th>
                                                <th>created_at</th>
                                                <th>Дествие</th>
                                            </tr>
                                            </thead>
                                            <tbody>

                                            @foreach($books as $book)
                                                <tr>
                                                    <td class="align-left">{{$book->id}}</td>
                                                    <td class="align-left">{!! Html::link(route('articless.edit',['articles'=>$book->id]),$book->name) !!}</td>
                                                    <td class="align-left">{{$book->email}}</td>
                                                    <td class="align-left">{{$book->text}}</td>
                                                    <td class="align-left">{{$book->created_at}}</td>

                                                    <td>
                                                        {!! Form::open(['url' => route('articless.destroy',['articles'=>$book->id]),'class'=>'form-horizontal','method'=>'POST']) !!}
                                                        {{ method_field('DELETE') }}
                                                        {!! Form::button('Удалить', ['class' => 'btn btn-french-5','type'=>'submit']) !!}
                                                        {!! Form::close() !!}
                                                    </td>
                                                </tr>
                                            @endforeach

                                            </tbody>
                                        </table>
                                    </div>



                                </div>
                                <!-- START COMMENTS -->
                                <div id="comments">
                                </div>
                                <!-- END COMMENTS -->
                            </div>
                        @endif

        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{  'Головна' }}
                    </a>
                    <a class="navbar-brand" href="{{ url('admin/articless') }}">
                        {{  'Book' }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/site.blade.php
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, maximum-scale=1">
    <title>Тестове завдання</title>
    <link rel="icon" href="{{asset('assets/favicon.png')}}" type="image/png">
    <link href="{{asset('assets/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('assets/css/style.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('assets/css/font-awesome.css')}}"rel="stylesheet" type="text/css">
    <link href="{{asset('assets/css/animate.css')}}" rel="stylesheet" type="text/css">

    <!--[if lt IE 9]>
    <script src="{{asset('assets/js/respond-1.1.0.min.js')}}"></script>
    <script src="{{asset('assets/js/html5shiv.js')}}"></script>
    <script src="{{asset('assets/js/html5element.js')}}"></script>
    <![endif]-->

</head>
<body>

<!--Header_section-->
<header id="header_wrapper">
    @yield('header')
</header>
<!--Header_section-->

<!--Hero_Section-->

    @yield('content')

<script type="text/javascript" src="{{asset('assets/js/jquery-1.11.0.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/js/bootstrap.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/js/jquery-scrolltofixed.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/js/jquery.nav.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/js/jquery.easing.1.3.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/js/jquery.isotope.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/js/wow.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/js/custom.js')}}"></script>

</body>
</html>

resources/views/site/articles.blade.php
@extends('layouts.site')


@section('content')

    <div class="container">
        <div class="row">
            <div class="row">
                <div class="center-block wow fadeInLeft delay-02s">
                    <div class="form">
                        <form action="{{route('articless.update',['articles'=>$date->id])}}" method="POST">
                            <div class="detail">
                                <h4>Name</h4>
                            </div>
                            <input class="input-text" type="text" name="name" value="{{$date->name}}" onFocus="if(this.value==this.defaultValue)this.value='';" onBlur="if(this.value=='')this.value=this.defaultValue;">
                            <div class="detail">
                                <h4>Email</h4>
                            </div>
                            <input class="input-text" type="text" name="email" value="{{$date->email}}"  onFocus="if(this.value==this.defaultValue)this.value='';" onBlur="if(this.value=='')this.value=this.defaultValue;">
                            <div class="detail">
                                <h4>Text</h4>
                            </div>
                            <textarea name="text" class="input-text text-area" cols="0" rows="0" onFocus="if(this.value==this.defaultValue)this.value='';" onBlur="if(this.value=='')this.value=this.defaultValue;">{{$date->text}}</textarea>

                            @if(isset($date->id))
                                <input type="hidden" name="_method" value="PUT">

                            @endif


                            <input class="input-btn" type="submit" value="send message">

                            {{ csrf_field() }}

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/site/book.blade.php
@extends('layouts.site')

@section('content')
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <a class="navbar-brand" href="{{ url('/') }}">
        {{  'Головна' }}
    </a>
    <a class="navbar-brand" href="{{ url('admin') }}">
        {{  'Admin' }}
    </a>
    <br><br>
        <div class="container">
            <div class="row">
                <div class="row">
                        <div class="center-block wow fadeInLeft delay-02s">
                            <div class="form">
                                <form action="{{route('article.store')}}" method="post">
                                    <div class="detail">
                                        <h4>Name</h4>
                                    </div>
                                    <input class="input-text" type="text" name="name"  onFocus="if(this.value==this.defaultValue)this.value='';" onBlur="if(this.value=='')this.value=this.defaultValue;">
                                    <div class="detail">
                                        <h4>Email</h4>
                                    </div>
                                    <input class="input-text" type="text" name="email"  onFocus="if(this.value==this.defaultValue)this.value='';" onBlur="if(this.value=='')this.value=this.defaultValue;">
                                    <div class="detail">
                                        <h4>Text</h4>
                                    </div>
                                    <textarea name="text" class="input-text text-area" cols="0" rows="0" onFocus="if(this.value==this.defaultValue)this.value='';" onBlur="if(this.value=='')this.value=this.defaultValue;"></textarea>
                                    <input class="input-btn" type="submit" value="send message">

                                    {{ csrf_field() }}

                                </form>


                            </div>
                        </div>
                </div>
        </div>



            <section class="page_section contact" id="contact">

                <div >
                    <h2>Гостевая книга</h2>
                </div>


            <div class="container">
                <div class="row">
                    <div class="row">
                        <div class="center-block wow fadeInLeft delay-02s">

                                        @if ($books)
                                            @foreach($books as $k=>$book)
                                            <div class="detail">
                                                <h4>Имя : {{$book->name}} </h4>
                                            </div>
                                            <div class="detail">
                                                <h4>Email : {{$book->email}}</h4>
                                            </div>
                                            <div class="detail">
                                                <h4>Текст : {{$book->text}}</h4>
                                            </div>
                                                <div class="detail">
                                                    <h4>Дата створення : {{$book->created_at}}</h4>
                                                </div>
                                                <div class="borderTop"></div>
                                                <br>
                                        @endforeach
                                    @endif
                                     </div>

                                    <ul class="social_links">
                                        <li class="twitter animated bounceIn wow delay-02s"><a href="javascript:void(0)"><i class="fa fa-twitter"></i></a></li>
                                        <li class="facebook animated bounceIn wow delay-03s"><a href="javascript:void(0)"><i class="fa fa-facebook"></i></a></li>
                                        <li class="pinterest animated bounceIn wow delay-04s"><a href="javascript:void(0)"><i class="fa fa-pinterest"></i></a></li>
                                        <li class="gplus animated bounceIn wow delay-05s"><a href="javascript:void(0)"><i class="fa fa-google-plus"></i></a></li>
                                    </ul>
                                </div>
                </div>
            </div>
            </section>
@endsection

resources/views/site/content.blade.php
<div style="margin:0px 50px 0px 50px;">

    @if($pages)
        <a class="navbar-brand" href="{{ url('article') }}">
            {{  'Гостевая книга' }}
        </a>
        <a class="navbar-brand" href="{{ url('admin') }}">
            {{  'Admin' }}
        </a>
        <table class="table table-hover table-striped table-bordered">
            <thead>
            <tr>
                <th class="text-center">Name</th>
                <th class="text-center">Phone</th>
            </tr>
            </thead>
            <tbody>
            @foreach($pages as $page)

                <tr>
                    <td>{{$page->name}}</td>
                    @if(is_object($page->phone))
                    <td>{{$page->phone->Phone}}</td>
                    @else
                        <td>--</td>
                    @endif
                </tr>

            @endforeach

            </tbody>
        </table>

    @endif

        @if($inquiry)
            <h5>Все фирмы, не имеющие телефонов : @foreach ($inquiry as $item)
                    {{$item->name}}
                @endforeach
            </h5>
        @endif
        @if($inquiry2)
            <h5>Все фирмы, имеющие не менее 2-х телефонов : @foreach ($inquiry2 as $item)
                    {{$item->name}}
                @endforeach
            </h5>
        @endif
        @if($inquiry3)
            <h5>Все фирмы, имеюшие менее 2-х телефонов : @foreach ($inquiry3 as $item)
                    {{$item->name}}
                @endforeach
            </h5>
        @endif
        @if($inquiry4)
            <h5>Фирма, имеющая максимальное кол-во телефонов : @foreach ($inquiry4 as $item)
                    {{$item->name}}
                @endforeach
            </h5>
        @endif



</div>

resources/views/site/index.blade.php
@extends('layouts.site')

@section('content')
    @include('site.content')
@endsection